# run/svencraft/skill.cfg: the SDK's per-difficulty skill cvars (sk_<name>1/2/3), filled with Sven Co-op's
# balance (its skill.cfg has one value per name) so monsters have Sven's health and damage
import re
import sc_paths   # project paths (tools/sc_paths.py)
ROOT = sc_paths.ROOT
game = re.sub(r'//.*', '', open(ROOT + r'\game\dlls\game.cpp').read())    # not the names in comments
bases = sorted(set(re.findall(r'"(sk_[A-Za-z0-9_]+?)[123]"', game)))
sven = {}
for line in open(ROOT + r'\run\svencoop\skill.cfg'):
    m = re.match(r'\s*(sk_\w+)\s+"?([-\d.]+)"?', line)
    if m:
        sven[m.group(1)] = m.group(2)
fallback = {'sk_plr_egon_narrow': '6', 'sk_plr_xbow_bolt': '50', 'sk_plr_xbow_bolt_client': '10'}
# Opposing Force's names (dlls/gearbox): Sven's own name for the same thing where it has one ('=name'), else
# Opposing Force's skillopfor.cfg value
fallback.update({
    'sk_hgrunt_ally_health': '=sk_hgrunt_health', 'sk_hgrunt_ally_kick': '=sk_hgrunt_kick',
    'sk_hgrunt_ally_pellets': '=sk_hgrunt_pellets', 'sk_hgrunt_ally_gspeed': '=sk_hgrunt_gspeed',
    'sk_medic_ally_health': '=sk_hgrunt_health', 'sk_medic_ally_kick': '=sk_hgrunt_kick',
    'sk_medic_ally_gspeed': '=sk_hgrunt_gspeed', 'sk_medic_ally_heal': '25',
    'sk_torch_ally_health': '=sk_hgrunt_health', 'sk_torch_ally_kick': '=sk_hgrunt_kick',
    'sk_torch_ally_gspeed': '=sk_hgrunt_gspeed',
    'sk_massassin_health': '=sk_hgrunt_health', 'sk_massassin_kick': '=sk_hgrunt_kick',
    'sk_massassin_gspeed': '=sk_hgrunt_gspeed',
    'sk_shocktrooper_gspeed': '=sk_hgrunt_gspeed', 'sk_shocktrooper_rchgspeed': '1',
    'sk_babyvoltigore_health': '60', 'sk_babyvoltigore_dmg_punch': '15',
    'sk_cleansuit_scientist_health': '=sk_scientist_health', 'sk_cleansuit_scientist_heal': '=sk_scientist_heal',
    'sk_shockroach_health': '10', 'sk_shockroach_dmg_bite': '10', 'sk_shockroach_lifespan': '10',
    'sk_geneworm_health': '1000', 'sk_geneworm_dmg_spit': '15', 'sk_geneworm_dmg_hit': '15',
    'sk_pitworm_health': '1000', 'sk_pitworm_dmg_swipe': '30', 'sk_pitworm_dmg_beam': '10',
    'sk_plr_556_bullet': '=sk_556_bullet', 'sk_plr_pipewrench': '=sk_plr_wrench', 'sk_plr_eagle': '34',
    'sk_plr_knife': '10', 'sk_plr_displacer_self': '=sk_plr_displacer_other',
    'sk_plr_shockroachs': '=sk_plr_shockrifle', 'sk_plr_shockroachm': '=sk_plr_shockrifle',
})
for k, v in list(fallback.items()):
    if v.startswith('='):
        fallback[k] = sven[v[1:]]
out = ['// generated by tools/make_skillcfg.py from Sven Co-op\'s skill.cfg']
for b in bases:
    v = sven.get(b, fallback.get(b))
    if v is None:
        raise SystemExit('no value for ' + b)
    out += ['%s%d "%s"' % (b, k, v) for k in (1, 2, 3)]
open(ROOT + r'\run\svencraft\skill.cfg', 'w', newline='\n').write('\n'.join(out) + '\n')
print(len(bases), 'skill values')
