# svencraft_sandbox: the Svencraft test sandbox (realistic map). A small Half-Life-style town on a road through hills,
# Sven Co-op textures and props, brush-built cars, and one rift: a torn crater where the Minecraft block
# world shows through (the block world itself is generated by the game DLL under the whole map).
import os, math, random, shutil, struct
import numpy as np
from PIL import Image
import sys
from maplib import Brush, box, prism, cylinder_y, cylinder_x, entity, write_wad, compile_map, write_dyn, SVEN
import town_v3
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'tools'))
import wadtex
import sc_paths   # project paths (tools/sc_paths.py; env overrides SVENCRAFT_GAMEDIR / _SDK / _SVEN)

HERE = os.path.dirname(os.path.abspath(__file__))
GAME = sc_paths.GAMEDIR
NAME = 'svencraft_sandbox'   # the test sandbox: every new concept lands here first
rng = random.Random(7)
nrng = np.random.default_rng(7)

H = 2048                  # half size of the playable area
SLAB = -160               # bottom of the realistic ground: the block world's top (4 blocks of 40 below 0)
FLOOR, TOP = -1040, 1792  # bedrock floor under the block world, sky height
RIFT = (1150, 760, 330)   # x, y, radius of the torn crater
POND = (-768, 976, 220, 180, -8)        # x, y, x and y radius, water level: the pond in the field behind the back alley
POND_AREA = (-1024, 768, -512, 1280)    # the ground cells its hollow replaces

# ---------------------------------------------------------------- custom textures (cars)
def paint(color, w, h, seed):
    r = np.random.default_rng(seed)
    base = np.array(color, float)
    y = np.linspace(1.08, 0.82, h)[:, None, None]          # lighter at the top, like sky reflection
    img = base * y + r.normal(0, 3, (h, w, 1))
    dirt = r.random((h, w)) < 0.015
    img[dirt] *= 0.75
    return np.clip(img, 0, 255)


def car_side(color, seed):
    w, h = 256, 64
    img = paint(color, w, h, seed)
    img[h // 2 - 1: h // 2 + 1] *= 0.7                      # body crease
    for x in (92, 150, 200):                                 # door seams
        img[6:h - 6, x: x + 2] *= 0.45
    for x in (130, 186):                                     # handles
        img[22:26, x: x + 12] = (40, 40, 40)
    for cx in (52, 204):                                     # wheel arches (dark)
        for yy in range(h):
            for xx in range(cx - 34, cx + 35):
                if (xx - cx) ** 2 + (yy - h - 6) ** 2 < 36 ** 2:
                    img[yy, xx] = (18, 18, 18)
    img[h - 4:] *= 0.5
    return img


def car_front(seed):
    w, h = 128, 32
    img = np.zeros((h, w, 3)) + (35, 35, 38)
    for yy in range(8, 24, 4):
        img[yy: yy + 2, 36: 92] = (80, 80, 84)               # grille bars
    for x0 in (6, 98):
        img[8:22, x0: x0 + 24] = (235, 232, 205)             # headlights
        img[10:20, x0 + 2: x0 + 22] = (255, 252, 230)
    img[26:] = (60, 60, 64)                                  # bumper
    return img


def car_back(seed):
    w, h = 128, 32
    img = np.zeros((h, w, 3)) + (40, 40, 44)
    for x0 in (6, 98):
        img[8:20, x0: x0 + 24] = (170, 20, 20)               # tail lights
        img[10:18, x0 + 2: x0 + 22] = (220, 40, 30)
    img[10:20, 48:80] = (210, 210, 200)                      # plate
    img[13:17, 52:76] = (40, 40, 60)
    img[26:] = (60, 60, 64)
    return img


def car_window(seed):
    w = h = 64
    img = np.zeros((h, w, 3)) + (38, 48, 58)
    yy, xx = np.mgrid[0:h, 0:w]
    streak = np.abs((xx + yy) - 40) < 7
    img[streak] = (90, 105, 120)
    img += nrng.normal(0, 2, img.shape)
    return np.clip(img, 0, 255)


TEX = {}
COLORS = {'red': (150, 28, 24), 'blue': (32, 58, 120), 'white': (205, 205, 200), 'black': (28, 28, 30), 'green': (40, 85, 50)}
for i, (cname, c) in enumerate(COLORS.items()):
    TEX['car_' + cname] = paint(c, 64, 64, i)
    TEX['carside_' + cname] = car_side(c, 10 + i)
TEX['car_front'] = car_front(1)
TEX['car_back'] = car_back(2)
TEX['car_window'] = car_window(3)
TEX['car_under'] = np.zeros((16, 16, 3)) + 22
TEX['car_chrome'] = np.clip(np.linspace(200, 120, 16)[:, None, None] + np.zeros((16, 16, 3)), 0, 255)

town_v3.textures(TEX, car_side, paint)    # signs, the police livery


def charred(img, seed):
    """the same texture after the car burned out: soot-black, paint gone grey, rust coming through"""
    r = np.random.default_rng(seed)
    h, w = img.shape[:2]
    def smooth(cell):
        small = (r.random((max(h // cell, 2), max(w // cell, 2))) * 255).astype(np.uint8)
        return np.array(Image.fromarray(small).resize((w, h), Image.BILINEAR), float)[:, :, None] / 255.0
    luma = img.mean(axis=2, keepdims=True)
    out = img * 0.25 + luma * 0.75
    out = out * (0.10 + 0.22 * smooth(6)) + r.normal(0, 4, (h, w, 1))
    rust = np.clip((smooth(4) - 0.55) * 3.0, 0, 1) * np.clip(r.random((h, w, 1)) * 1.5, 0, 1)
    out = out * (1 - rust * 0.7) + np.array((96, 50, 24)) * rust * 0.7
    return np.clip(out, 0, 255)


# what a car's textures turn into when it burns out (sc_car swaps its model for the burnt copy)
BURNT = {}
for k, name in enumerate([n for n in TEX if n.startswith('car')]):
    BURNT[name] = 'cb' + name[3:]
    TEX[BURNT[name]] = charred(TEX[name], 40 + k)
BURNT['TIRE_01'] = 'car_under'
bed = np.clip(np.array((60, 60, 62.0)) + nrng.normal(0, 14, (64, 64, 1)), 0, 255)
TEX['sc_bedrock'] = bed


def water_texture(src, fog, density):
    """a copy of a Half-Life water texture with its own underwater fog: the engine takes the fog's colour from
    palette entry 3 and its density from entry 4's red (img_wad.c); pixels that used those entries move to the
    nearest other colour"""
    w, path, fo = wadtex.index()[src.upper()]
    d = open(path, 'rb').read()
    wd, hg, o0, o1, o2, o3 = struct.unpack_from('<II4I', d, fo + 16)
    idx = np.frombuffer(d[fo + o0: fo + o0 + wd * hg], np.uint8).reshape(hg, wd).copy()
    palo = fo + o3 + (wd // 8) * (hg // 8) + 2
    pal = np.frombuffer(d[palo: palo + 768], np.uint8).reshape(256, 3).astype(int)
    for k in (3, 4):
        dist = ((pal - pal[k]) ** 2).sum(1)
        dist[[3, 4]] = 1 << 30
        idx[idx == k] = int(dist.argmin())
    pal = pal.copy()
    pal[3], pal[4] = fog, (density, 0, 0)
    im = Image.fromarray(idx, 'P')
    im.putpalette(pal.astype(np.uint8).flatten().tolist())
    return im


# the pond's water: Half-Life's c2a5 dam water, murkier underneath (you see a couple of metres, not across it)
WATER_TEX = {'!pondwater': water_texture('!C2A53', (34, 42, 28), 255)}   # (255: the densest the engine takes)
wadpath = os.path.join(HERE, 'svencraft_sandbox.wad')
write_wad(wadpath, dict({k: Image.fromarray(v.astype(np.uint8), 'RGB') for k, v in TEX.items()}, **WATER_TEX))

# ---------------------------------------------------------------- terrain
def smoothstep(a, b, x):
    t = min(max((x - a) / (b - a), 0.0), 1.0)
    return t * t * (3 - 2 * t)


def vnoise(x, y, scale, seed):
    """cheap smooth 2D value noise in [-1, 1]"""
    x, y = x / scale, y / scale
    xi, yi = math.floor(x), math.floor(y)
    def h(i, j):
        return random.Random((i * 73856093) ^ (j * 19349663) ^ seed).uniform(-1, 1)
    fx, fy = x - xi, y - yi
    fx, fy = fx * fx * (3 - 2 * fx), fy * fy * (3 - 2 * fy)
    a = h(xi, yi) + (h(xi + 1, yi) - h(xi, yi)) * fx
    b = h(xi, yi + 1) + (h(xi + 1, yi + 1) - h(xi, yi + 1)) * fx
    return a + (b - a) * fy


FLAT = [(-1400, -900, 700, 1024), (700, -1000, 1450, -128)]   # the town, the gas station's lot


def flat_dist(x, y):
    """distance outside the flat zone (the road strip plus the town rectangles)"""
    d = abs(y) - 320
    for x0, y0, x1, y1 in FLAT:
        dx = max(x0 - x, 0, x - x1)
        dy = max(y0 - y, 0, y - y1)
        d = min(d, math.hypot(dx, dy) if (dx or dy) else -1)
    return max(d, 0)


def height(x, y):
    d = flat_dist(x, y)
    hill = smoothstep(0, 900, d) * (170 + 110 * vnoise(x, y, 700, 1) + 45 * vnoise(x, y, 260, 2))
    edge = max(abs(x), abs(y)) - 1450
    mountain = (max(edge, 0) / 600.0) ** 2 * 420
    return int(round((hill + mountain) / 8.0)) * 8


G = 256
N = 2 * H // G
grid = [[height(-H + i * G, -H + j * G) for j in range(N + 1)] for i in range(N + 1)]


def surface_z(x, y):
    """height of the triangulated ground at (x, y), same triangle split as the brushes below"""
    i = min(max(int((x + H) // G), 0), N - 1)
    j = min(max(int((y + H) // G), 0), N - 1)
    fx, fy = (x + H - i * G) / G, (y + H - j * G) / G
    z00, z10, z11, z01 = grid[i][j], grid[i + 1][j], grid[i + 1][j + 1], grid[i][j + 1]
    if (i + j) % 2 == 0:
        if fx >= fy:
            return z00 + fx * (z10 - z00) + fy * (z11 - z10)
        return z00 + fy * (z01 - z00) + fx * (z11 - z01)
    if fx + fy <= 1:
        return z00 + fx * (z10 - z00) + fy * (z01 - z00)
    return z11 + (1 - fx) * (z01 - z11) + (1 - fy) * (z10 - z11)


def pond_depth(x, y):
    """how far the pond's hollow sinks below the ground at (x, y): a bowl with a ragged shore, deeper to the north"""
    px, py, rx, ry, _ = POND
    r = math.hypot((x - px) / rx, (y - py) / ry) * (1 + 0.12 * vnoise(x, y, 140, 21))
    return (88 + 24 * smoothstep(py - ry, py + ry, y)) * smoothstep(1.0, 0.3, r)


def ground_z(x, y):
    """the ground's height, with the pond's hollow"""
    ax0, ay0, ax1, ay1 = POND_AREA
    return surface_z(x, y) - (pond_depth(x, y) if ax0 <= x <= ax1 and ay0 <= y <= ay1 else 0)


world = []
dyn = []        # diggable brushes: (Brush, material block id, cut texture)
for i in range(N):
    for j in range(N):
        x0, y0 = -H + i * G, -H + j * G
        cx, cy = x0 + G / 2, y0 + G / 2
        if math.hypot(cx - RIFT[0], cy - RIFT[1]) < RIFT[2]:
            continue                                         # the rift: no realistic ground here
        if POND_AREA[0] < cx < POND_AREA[2] and POND_AREA[1] < cy < POND_AREA[3]:
            continue                                         # the pond's hollow (below)
        corners = [(x0, y0, grid[i][j]), (x0 + G, y0, grid[i + 1][j]), (x0 + G, y0 + G, grid[i + 1][j + 1]), (x0, y0 + G, grid[i][j + 1])]
        tris = [(0, 1, 2), (0, 2, 3)] if (i + j) % 2 == 0 else [(0, 1, 3), (1, 2, 3)]
        for t in tris:
            pts = [corners[k] for k in t]
            zs = [p[2] for p in pts]
            slope = (max(zs) - min(zs)) / G
            top = 'OUT_ROCK4' if slope > 0.85 else ('OUT_DIRT1' if slope > 0.5 else 'rocky_grass_01')
            if top == 'rocky_grass_01' and flat_dist(cx, cy) > 200:
                n = vnoise(cx, cy, 900, 11)
                top = 'OUT_GROUND9' if n > 0.4 else ('jungle_floor_02' if n < -0.45 else top)
            # the ground is diggable: it goes to the .dyn file, not the BSP (material 2 = the dirt block)
            dyn.append((prism([(p[0], p[1]) for p in pts], SLAB, zs, top, 'OUT_DIRT1', 'OUT_DIRT1'), 2, 'OUT_DIRT1'))

# the pond's hollow: its ground cells again on a finer grid (32 units around the water, 64 elsewhere; one grid, so
# no seams), the same diggable dirt: grass, a muddy bank, a dirt bed under the water
ax0, ay0, ax1, ay1 = POND_AREA
def pond_lines(a0, a1, c, r):
    w0, w1 = int(c - 1.2 * r) // 32 * 32, int(c + 1.2 * r) // 32 * 32 + 32
    return sorted(set(range(a0, a1 + 1, 64)) | {a for a in range(w0, w1 + 1, 32) if a0 <= a <= a1})
pxs, pys = pond_lines(ax0, ax1, POND[0], POND[2]), pond_lines(ay0, ay1, POND[1], POND[3])
pz = {(x, y): int(round(ground_z(x, y))) for x in pxs for y in pys}
for i in range(len(pxs) - 1):
    for j in range(len(pys) - 1):
        c = [(pxs[i], pys[j]), (pxs[i + 1], pys[j]), (pxs[i + 1], pys[j + 1]), (pxs[i], pys[j + 1])]
        z = [pz[p] for p in c]
        # split each square along the diagonal whose ends differ least: the smoother surface
        for t in ([(0, 1, 2), (0, 2, 3)] if abs(z[0] - z[2]) <= abs(z[1] - z[3]) else [(0, 1, 3), (1, 2, 3)]):
            zs = [z[k] for k in t]
            dug = max(surface_z(*c[k]) - z[k] for k in t)
            top = 'OUT_DIRT2' if max(zs) < POND[4] - 4 else ('OUT_DIRT1' if dug > 2 else 'rocky_grass_01')
            dyn.append((prism([c[k] for k in t], SLAB, zs, top, 'OUT_DIRT1', 'OUT_DIRT1'), 2, 'OUT_DIRT1'))

# block ids of the realistic materials (game/dlls/svencraft/sc_world.h)
B_DIRT, B_COBBLE, B_BRICK, B_TAN_BRICK, B_CONCRETE, B_ASPHALT = 2, 4, 18, 19, 20, 21
MATERIAL = {'WALL_BRICK1': B_BRICK, 'PRXBRICK1A': B_BRICK, 'WALL_BRICK3': B_TAN_BRICK, 'OUT_CONCRETE1': B_CONCRETE,
            'conc_wall_01': B_CONCRETE, 'stucco_01': B_CONCRETE}

# road (east-west) with sidewalks through town; all diggable
dyn.append((box((-H, -128, 0), (H, 128, 2), {'top': 'road2', 'side': 'OUT_ASPHALT1', 'bottom': 'OUT_ASPHALT1'},
                top={'u': (0, 1, 0), 'v': (1, 0, 0), 'shift': (128, 0)}), B_ASPHALT, 'OUT_ASPHALT1'))
SIDEWALK = {'top': 'OUT_SIDEWALK1', 'side': 'IN_CURB1', 'bottom': 'IN_CURB1'}
for x0, y0, x1, y1 in ((-1400, 128, 40, 192), (200, 128, 700, 192), (-1400, -192, 700, -128)):
    dyn.append((box((x0, y0, 0), (x1, y1, 8), SIDEWALK), B_CONCRETE, 'OUT_CONCRETE1'))
# Elm St, north from the main road to the church; its sidewalks, the church's cobbled forecourt
dyn.append((box((40, 128, 0), (200, 768, 2), {'top': 'road2', 'side': 'OUT_ASPHALT1', 'bottom': 'OUT_ASPHALT1'},
                top={'u': (1, 0, 0), 'v': (0, -1, 0), 'shift': (-64, 0), 'scale': (0.625, 1)}), B_ASPHALT, 'OUT_ASPHALT1'))
for x0, x1 in ((0, 40), (200, 240)):
    dyn.append((box((x0, 192, 0), (x1, 768, 8), SIDEWALK), B_CONCRETE, 'OUT_CONCRETE1'))
dyn.append((box((0, 768, 0), (240, 792, 2), {'top': 'cobble1a', 'side': 'OUT_CONCRETE1'}), B_COBBLE, 'cobble1a'))
# road paint: a zebra crossing over the main road east of the junction and one over Elm St, a stop line
for k in range(8):
    y = -120 + 32 * k
    dyn.append((box((216, y, 2), (312, y + 16, 3), 'WHITE'), B_ASPHALT, 'OUT_ASPHALT1'))
for k in range(5):
    x = 48 + 32 * k
    dyn.append((box((x, 208, 2), (x + 16, 296, 3), 'WHITE'), B_ASPHALT, 'OUT_ASPHALT1'))
dyn.append((box((40, 304, 2), (120, 312, 3), 'WHITE'), B_ASPHALT, 'OUT_ASPHALT1'))
# parking lot by the warehouse
dyn.append((box((-1280, -1000, 0), (-560, -192, 2), {'top': 'DOUBLE_ASPHALT', 'side': 'OUT_ASPHALT1'}), B_ASPHALT, 'OUT_ASPHALT1'))

# bedrock floor and sky box
world.append(box((-H, -H, FLOOR - 32), (H, H, FLOOR), 'sc_bedrock'))
for mn, mx in (((-H - 32, -H - 32, TOP), (H + 32, H + 32, TOP + 32)), ((-H - 32, -H - 32, FLOOR - 32), (-H, H + 32, TOP)),
               ((H, -H - 32, FLOOR - 32), (H + 32, H + 32, TOP)), ((-H, -H - 32, FLOOR - 32), (H, -H, TOP)), ((-H, H, FLOOR - 32), (H, H + 32, TOP))):
    world.append(box(mn, mx, 'sky'))

ents = []

# ---------------------------------------------------------------- buildings
def wall(axis, fixed0, fixed1, a0, a1, h, openings, tex_out, tex_in, out_side):
    """Wall along `axis` ('x' or 'y') between a0..a1, thickness fixed0..fixed1, height 0..h (on an 8-unit floor),
    minus openings [(o0, o1, z0, z1)]. out_side: '+' or '-' (which thickness side faces outdoors)."""
    cuts = sorted({a0, a1} | {o[0] for o in openings} | {o[1] for o in openings})
    out = []
    other = 'y' if axis == 'x' else 'x'
    tex = {'all': tex_in, other + out_side: tex_out, 'top': tex_out}
    for s0, s1 in zip(cuts, cuts[1:]):
        holes = sorted((o[2], o[3]) for o in openings if o[0] <= s0 and o[1] >= s1)
        z = 8
        for z0, z1 in holes + [(h, h)]:
            if z0 > z:
                if axis == 'x':
                    out.append(box((s0, fixed0, z), (s1, fixed1, z0), tex))
                else:
                    out.append(box((fixed0, s0, z), (fixed1, s1, z0), tex))
            z = max(z, z1)
    return out


def glass(axis, fixed0, fixed1, o):
    if axis == 'x':
        b = box((o[0], fixed0 + 6, o[2]), (o[1], fixed1 - 6, o[3]), 'GLASS_DARK')
    else:
        b = box((fixed0 + 6, o[0], o[2]), (fixed1 - 6, o[1], o[3]), 'GLASS_DARK')
    return entity({'classname': 'func_breakable', 'material': '0', 'health': '20', 'rendermode': '2', 'renderamt': '110'}, [b])


def prop(model, x, y, yaw=None, solid=True, z=None):
    zz = surface_z(x, y) if z is None else z
    ents.append(entity({'classname': 'sc_prop', 'model': model, 'origin': '%d %d %d' % (x, y, zz),
                        'angles': '0 %d 0' % (rng.randint(0, 359) if yaw is None else yaw), 'solid': '2' if solid else '0'}))


BUILDINGS, DOORS, CARS = [], [], []    # footprints, doorways (x, y, outward normal) and cars, for the AI nodes
FURNITURE = []                          # footprints of what stands inside (x0, y0, x1, y1): no AI nodes there
B_PLANKS, B_METAL = 15, 22


def fit(u, v, origin_u, origin_v, size_u, size_v, tw, th):
    """face texinfo: texture of tw x th pixels stretched over size_u x size_v units starting at (origin_u, origin_v)"""
    su, sv = size_u / tw, size_v / th
    return {'u': u, 'v': v, 'shift': (-origin_u / su, origin_v / sv), 'scale': (su, sv)}


def dbox(mn, mx, tex, mat, cut=None, **kw):
    """a diggable box: it gives `mat` when dug, and shows `cut` (default: its side texture) where it is cut open"""
    b = box(mn, mx, tex, **kw)
    if cut is None:
        cut = tex if isinstance(tex, str) else (tex.get('side') or tex.get('all') or next(iter(tex.values())))
    dyn.append((b, mat, cut))
    return b


def side_box(side, face, a0, a1, z0, z1, depth, tex, mat):
    """a box against a building's outer face on `side` ('x-', 'x+', 'y-', 'y+'), from a0 to a1 along it"""
    if side == 'y-':
        return dbox((a0, face - depth, z0), (a1, face, z1), tex, mat)
    if side == 'y+':
        return dbox((a0, face, z0), (a1, face + depth, z1), tex, mat)
    if side == 'x-':
        return dbox((face - depth, a0, z0), (face, a1, z1), tex, mat)
    return dbox((face, a0, z0), (face + depth, a1, z1), tex, mat)


def door(side, wall0, wall1, a, z0=8, z1=120, tex='DOOR_02'):
    """a Half-Life door (func_door_rotating, opens away from whoever pushes it) in the doorway centred at `a`"""
    c = (wall0 + wall1) / 2
    tw, th = wadtex.load(tex)[0].size     # the whole door texture on the panel
    if side in ('y-', 'y+'):
        f = fit((1, 0, 0), (0, 0, -1), a - 30, z1, 60, z1 - z0, tw, th)
        panel = box((a - 30, c - 2, z0), (a + 30, c + 2, z1), {'all': 'DOOR_MTL_01', 'y+': tex, 'y-': tex}, **{'y+': f, 'y-': f})
        origin = box((a - 32, c - 2, z0), (a - 28, c + 2, z1), 'ORIGIN')
    else:
        f = fit((0, 1, 0), (0, 0, -1), a - 30, z1, 60, z1 - z0, tw, th)
        panel = box((c - 2, a - 30, z0), (c + 2, a + 30, z1), {'all': 'DOOR_MTL_01', 'x+': tex, 'x-': tex}, **{'x+': f, 'x-': f})
        origin = box((c - 2, a - 32, z0), (c + 2, a - 28, z1), 'ORIGIN')
    ents.append(entity({'classname': 'func_door_rotating', 'speed': '140', 'distance': '90', 'wait': '5', 'movesnd': '1',
                        'stopsnd': '1', 'angles': '0 0 0', 'spawnflags': '0'}, [panel, origin]))


def crate(x, y, z, size=48, pushable=False):
    """Half-Life's wooden crate: shoot or smash it to pieces (func_breakable, wood); a pushable one slides when walked
    into (func_pushable, breakable too)"""
    f = {k: fit(u, (0, 0, -1), o, z + size, size, size, 64, 64) for k, u, o in
         (('x+', (0, 1, 0), y - size / 2), ('x-', (0, 1, 0), y - size / 2), ('y+', (1, 0, 0), x - size / 2), ('y-', (1, 0, 0), x - size / 2))}
    f['top'] = fit((1, 0, 0), (0, -1, 0), x - size / 2, -(y - size / 2), size, size, 64, 64)
    b = box((x - size / 2, y - size / 2, z), (x + size / 2, y + size / 2, z + size), 'CRATE02', **f)
    if pushable:
        ents.append(entity({'classname': 'func_pushable', 'spawnflags': '128', 'material': '1', 'health': '30', 'friction': '50', 'size': '2'}, [b]))
    else:
        ents.append(entity({'classname': 'func_breakable', 'material': '1', 'health': '30', 'spawnobject': '0'}, [b]))
    FURNITURE.append((x - size / 2, y - size / 2, x + size / 2, y + size / 2))


def desk(cx, cy, facing, z=8):
    """Half-Life's office desk: a wooden top on a drawer pedestal and a panel leg; `facing` = where the sitter
    is ('y-', 'y+', 'x-', 'x+')"""
    L, W, H = 64, 32, 30
    along_x = facing in ('y-', 'y+')
    x0, x1, y0, y1 = (cx - L / 2, cx + L / 2, cy - W / 2, cy + W / 2) if along_x else (cx - W / 2, cx + W / 2, cy - L / 2, cy + L / 2)
    dbox((x0, y0, z + H - 2), (x1, y1, z + H), {'top': 'M_WOOD1', 'all': 'DESK_GEN'}, B_PLANKS)
    if along_x:
        f = fit((1, 0, 0), (0, 0, -1), x1 - 18, z + H - 2, 16, H - 2, 64, 64)
        dbox((x1 - 18, y0 + 2, z), (x1 - 2, y1 - 2, z + H - 2), {'all': 'DESK_GEN', facing: 'DESK_DRAWER1'}, B_PLANKS, **{facing: f})
        dbox((x0 + 2, y0 + 2, z), (x0 + 4, y1 - 2, z + H - 2), 'DESK_GEN', B_PLANKS)
    else:
        f = fit((0, 1, 0), (0, 0, -1), y1 - 18, z + H - 2, 16, H - 2, 64, 64)
        dbox((x0 + 2, y1 - 18, z), (x1 - 2, y1 - 2, z + H - 2), {'all': 'DESK_GEN', facing: 'DESK_DRAWER1'}, B_PLANKS, **{facing: f})
        dbox((x0 + 2, y0 + 2, z), (x1 - 2, y0 + 4, z + H - 2), 'DESK_GEN', B_PLANKS)
    FURNITURE.append((x0, y0, x1, y1))
    # and a chair for it
    off = {'y-': (0, -30, 90), 'y+': (0, 30, 270), 'x-': (-30, 0, 0), 'x+': (30, 0, 180)}[facing]
    prop('models/ginsmodels/gins_deskchair.mdl', cx + off[0], cy + off[1], yaw=off[2], z=z + 32)


def shelf(x0, y0, x1, y1, z=8, h=100, tex='BA_STEEL_01', mat=B_METAL):
    """a storage rack: two end frames and four boards (metal unless told otherwise)"""
    along_x = x1 - x0 > y1 - y0
    if along_x:
        dbox((x0, y0, z), (x0 + 2, y1, z + h), tex, mat)
        dbox((x1 - 2, y0, z), (x1, y1, z + h), tex, mat)
    else:
        dbox((x0, y0, z), (x1, y0 + 2, z + h), tex, mat)
        dbox((x0, y1 - 2, z), (x1, y1, z + h), tex, mat)
    for k in range(4):
        zz = z + 4 + k * (h - 8) / 3
        if along_x:
            dbox((x0 + 2, y0, zz), (x1 - 2, y1, zz + 2), tex, mat)
        else:
            dbox((x0, y0 + 2, zz), (x1, y1 - 2, zz + 2), tex, mat)
    FURNITURE.append((x0, y0, x1, y1))


def counter(x0, y0, x1, y1, z=8, h=40):
    dbox((x0, y0, z + h - 3), (x1, y1, z + h), {'top': 'M_WOOD1', 'all': 'WOOD_PANEL_01'}, B_PLANKS)
    dbox((x0 + 2, y0 + 2, z), (x1 - 2, y1 - 2, z + h - 3), 'WOOD_PANEL_01', B_PLANKS)
    FURNITURE.append((x0, y0, x1, y1))


# what each kind of building is like inside
KINDS = {
    'office':    {'floor': 'CARPET_TAN', 'ceil': 'CEILING_TILE', 'wall_in': 'WALL_PLASTER'},
    'shop':      {'floor': 'C1A1_LINO', 'ceil': 'CEILING_TILE', 'wall_in': 'WALL_PLASTER'},
    'warehouse': {'floor': 'CONCRETETILE', 'ceil': 'OUT_CONCRETE1', 'wall_in': 'conc_wall_01'},
    'house':     {'floor': 'EASTWOOD01', 'ceil': 'FIFTIES_CEIL01', 'wall_in': 'WALL_PLASTER'},
}
H1 = 128    # the upper floor of a two-storey building


def building(x0, y0, x1, y1, h, tex_out, kind, door_side, windows=2, roof='OUT_ROOF2', light=(255, 236, 200, 160),
             floors=1, gable=0, door_tex='DOOR_02', door_offset=0):
    """A Half-Life-style building, all of it diggable (each part gives its own material): framed windows with
    glass, a door in a steel frame, the kind's floor, ceiling and walls, upper floors (up to three storeys) up
    switchback stairs along the back wall, a flat roof with a parapet and an air conditioner, or a gable roof
    `gable` units high. Buildings with upper floors have their door on y- or y+ (the stairs climb the far wall)."""
    T = 16
    K = KINDS[kind]
    BUILDINGS.append((x0, y0, x1, y1))
    mat = MATERIAL.get(tex_out, B_CONCRETE)
    roof_mat = B_ASPHALT if roof in ('DOUBLE_ASPHALT', 'OUT_ROOF2') else mat
    dbox((x0, y0, 0), (x1, y1, 8), {'top': K['floor'], 'side': tex_out}, mat, cut='OUT_CONCRETE1')     # floor slab
    if gable:
        dbox((x0, y0, h), (x1, y1, h + 8), {'top': 'OUT_CONCRETE1', 'bottom': K['ceil'], 'side': tex_out}, mat)
        # two sloping halves, the ridge along the longer side, eaves 12 out with a 6-unit fascia
        if x1 - x0 >= y1 - y0:
            ym = (y0 + y1) / 2
            for ya, yb, za, zb in ((y0 - 12, ym, h + 14, h + 8 + gable), (ym, y1 + 12, h + 8 + gable, h + 14)):
                dyn.append((prism([(x0 - 12, ya), (x1 + 12, ya), (x1 + 12, yb), (x0 - 12, yb)], h + 8, [za, za, zb, zb], roof, tex_out, 'WOOD_PANEL_01'),
                            roof_mat, tex_out))
        else:
            xm = (x0 + x1) / 2
            for xa, xb, za, zb in ((x0 - 12, xm, h + 14, h + 8 + gable), (xm, x1 + 12, h + 8 + gable, h + 14)):
                dyn.append((prism([(xa, y0 - 12), (xb, y0 - 12), (xb, y1 + 12), (xa, y1 + 12)], h + 8, [za, zb, zb, za], roof, tex_out, 'WOOD_PANEL_01'),
                            roof_mat, tex_out))
    else:
        dbox((x0, y0, h), (x1, y1, h + 16), {'top': roof, 'bottom': K['ceil'], 'side': tex_out}, roof_mat)
        # parapet, and the roof's machinery
        for a in ((x0, y0, x1, y0 + 8), (x0, y1 - 8, x1, y1), (x0, y0 + 8, x0 + 8, y1 - 8), (x1 - 8, y0 + 8, x1, y1 - 8)):
            dbox((a[0], a[1], h + 16), (a[2], a[3], h + 40), {'top': 'OUT_CONCRETE1', 'side': tex_out}, mat)
        ax, ay = x0 + (x1 - x0) * 0.62, y0 + (y1 - y0) * 0.4
        dbox((ax - 32, ay - 24, h + 16), (ax + 32, ay + 24, h + 56), {'top': 'BA_STEEL_01', 'side': 'PRXVENT1'}, B_METAL)
        # the unit breathes out a little warm air (sc_emitter, game/dlls/svencraft/sc_emitter.cpp)
        ents.append(entity({'classname': 'sc_emitter', 'origin': '%d %d %d' % (ax, ay, h + 60), 'kind': '0', 'rate': '3', 'renderamt': '45', 'scale': '0.4'}))
        dbox((ax - 70, ay + 30, h + 16), (ax - 58, ay + 42, h + 52), 'BA_STEEL_01', B_METAL)

    if floors == 3:
        rows = [(48, 104), (168, 224), (288, 344)]
    elif floors == 2:
        rows = [(56, 112), (160, 208)]
    else:
        rows = [(64, 128)] + ([(160, 208)] if h > 200 else [])

    def win_list(a0, a1, door_at):
        ops = []
        for k in range(windows):
            c = a0 + (a1 - a0) * (k + 1) / (windows + 1)
            if door_at is not None and abs(c - door_at) < 96:
                continue
            c = int(c // 8 * 8)
            ops += [(c - 32, c + 32) + r for r in rows]
        if door_at is not None:
            ops.append((door_at - 32, door_at + 32, 8, 120))
        return ops

    mid_x, mid_y = int((x0 + x1) // 2 // 8 * 8) + door_offset, int((y0 + y1) // 2 // 8 * 8) + door_offset
    DOORS.append({'y-': (mid_x, y0, 0, -1), 'y+': (mid_x, y1, 0, 1), 'x-': (x0, mid_y, -1, 0), 'x+': (x1, mid_y, 1, 0)}[door_side])
    sides = {
        'y-': ('x', y0, y0 + T, x0, x1, '-', mid_x if door_side == 'y-' else None, y0),
        'y+': ('x', y1 - T, y1, x0, x1, '+', mid_x if door_side == 'y+' else None, y1),
        'x-': ('y', x0, x0 + T, y0 + T, y1 - T, '-', mid_y if door_side == 'x-' else None, x0),
        'x+': ('y', x1 - T, x1, y0 + T, y1 - T, '+', mid_y if door_side == 'x+' else None, x1),
    }
    for key, (axis, f0, f1, a0, a1, outs, door_at, face) in sides.items():
        ops = win_list(a0, a1, door_at)
        for b in wall(axis, f0, f1, a0, a1, h, ops, tex_out, K['wall_in'], outs):
            dyn.append((b, mat, tex_out))
        for o in ops:
            if o[2] > 8:
                ents.append(glass(axis, f0, f1, o))
                # a concrete sill under it and a lintel over it
                side_box(key, face, o[0] - 6, o[1] + 6, o[2] - 6, o[2], 6, 'OUT_CONCRETE1', B_CONCRETE)
                side_box(key, face, o[0] - 4, o[1] + 4, o[3], o[3] + 8, 2, 'OUT_CONCRETE1', B_CONCRETE)
            else:
                # the doorway: a steel frame, a step up to the floor, the door
                side_box(key, face, o[0] - 6, o[0], o[2], o[3] + 6, 2, 'BA_STEEL_01', B_METAL)
                side_box(key, face, o[1], o[1] + 6, o[2], o[3] + 6, 2, 'BA_STEEL_01', B_METAL)
                side_box(key, face, o[0], o[1], o[3], o[3] + 6, 2, 'BA_STEEL_01', B_METAL)
                side_box(key, face, o[0] - 16, o[1] + 16, 0, 6, 24, {'top': 'OUT_CONCRETE1', 'side': 'IN_CURB1'}, B_CONCRETE)
                door(key, f0, f1, (o[0] + o[1]) / 2, tex=door_tex)
                # a lamp over the door
                lx, ly = {'y-': (door_at, face - 14), 'y+': (door_at, face + 14), 'x-': (face - 14, door_at), 'x+': (face + 14, door_at)}[key]
                side_box(key, face, door_at - 10, door_at + 10, 140, 148, 12, {'all': 'BA_STEEL_01', 'bottom': 'streetlight1'}, B_METAL)
                ents.append(entity({'classname': 'light', 'origin': '%d %d 134' % (lx, ly), '_light': '255 214 150 70'}))

    # upper floors: slabs every 120 units with a stairwell over the flight that comes up through them. The
    # flights switch back along the back wall: the first rises +x in the strip against it, the next -x in front
    ix0, iy0, ix1, iy1 = x0 + T, y0 + T, x1 - T, y1 - T
    sx0, sx1 = ix0 + 24, ix0 + 24 + 160
    for f in range(1, floors):
        z = 8 + 120 * f
        if door_side == 'y+':                               # this flight's strip, f = 1 against the far wall
            strip = ( iy0 + 64 * ( f - 1 ), iy0 + 64 * f )
            hx0, hy0, hx1, hy1 = sx0 - 8, strip[0], sx1 + 8, strip[1] + 8
        else:
            strip = ( iy1 - 64 * f, iy1 - 64 * ( f - 1 ))
            hx0, hy0, hx1, hy1 = sx0 - 8, strip[0] - 8, sx1 + 8, strip[1]
        for a, b in (((ix0, iy0), (ix1, hy0)), ((ix0, hy0), (hx0, hy1)), ((hx1, hy0), (ix1, hy1)), ((ix0, hy1), (ix1, iy1))):
            if b[0] - a[0] >= 1 and b[1] - a[1] >= 1:
                dbox((a[0], a[1], z - 8), (b[0], b[1], z), {'top': K['floor'], 'bottom': K['ceil'], 'side': K['wall_in']}, mat,
                     cut='OUT_CONCRETE1')
        base = z - 120
        for k in range(8):
            xa, xb = ( sx0 + k * 20, sx0 + ( k + 1 ) * 20 ) if f % 2 else ( sx1 - ( k + 1 ) * 20, sx1 - k * 20 )
            dbox((xa, strip[0], base), (xb, strip[1], base + 15 * ( k + 1 )), {'top': '4_STEPS01', 'side': K['wall_in']}, mat,
                 cut='OUT_CONCRETE1')
        FURNITURE.append((sx0, strip[0], sx1, strip[1]))
        ents.append(entity({'classname': 'light', 'origin': '%d %d %d' % ((x0 + x1) // 2, (y0 + y1) // 2, z - 20),
                            '_light': '%d %d %d %d' % light}))
    ents.append(entity({'classname': 'light', 'origin': '%d %d %d' % ((x0 + x1) // 2, (y0 + y1) // 2, h - 24),
                        '_light': '%d %d %d %d' % light}))
    return ix0, iy0, ix1, iy1


# the office: reception and desks downstairs, more desks upstairs
ix0, iy0, ix1, iy1 = building(-1200, 384, -800, 704, 232, 'WALL_BRICK1', 'office', 'y-', windows=3, floors=2)
desk(-1110, 470, 'y+'); desk(-890, 470, 'y+'); desk(-860, 600, 'x-')
prop('models/filecabinet.mdl', ix0 + 14, 430, yaw=0, z=8); prop('models/filecabinet.mdl', ix0 + 14, 462, yaw=0, z=8)
prop('models/uplant1.mdl', ix1 - 20, iy0 + 20, z=8)
desk(-1120, 520, 'y-', z=H1); desk(-1000, 520, 'y-', z=H1); desk(-880, 520, 'y-', z=H1)
prop('models/filecabinet.mdl', ix1 - 14, 640, yaw=180, z=H1); prop('models/ginsmodels/gins_couch.mdl', ix0 + 4, 470, yaw=0, z=H1)

# the shop: a counter at the back, shelves along the sides, tables by the window
ix0, iy0, ix1, iy1 = building(-640, 384, -320, 640, 184, 'WALL_BRICK3', 'shop', 'y-', windows=2, roof='SLATE_ROOF_1', gable=56)
counter(-560, iy1 - 60, -400, iy1 - 36)
shelf(ix0 + 2, iy0 + 70, ix0 + 26, iy0 + 166); shelf(ix1 - 26, iy0 + 70, ix1 - 2, iy0 + 166)
for tx in (-570, -390):
    prop('models/ginsmodels/wb_table01.mdl', tx, 460, z=8)
    prop('models/chair.mdl', tx - 34, 460, yaw=0, z=8); prop('models/chair.mdl', tx + 34, 460, yaw=180, z=8)
prop('models/ginsmodels/gins_ceilfan.mdl', -480, 512, z=184, solid=False)
prop('models/uplant1.mdl', ix0 + 20, iy1 - 20, z=8)

# the warehouse: racks, stacks of crates, drums
ix0, iy0, ix1, iy1 = building(-1184, -832, -704, -384, 256, 'OUT_CONCRETE1', 'warehouse', 'y+', windows=3, roof='DOUBLE_ASPHALT',
                              light=(220, 230, 255, 140))
for k in range(3):
    shelf(ix0 + 30 + k * 120, iy0 + 20, ix0 + 126 + k * 120, iy0 + 50, h=120)
for x, y, z in ((-1100, -610, 8), (-1100, -560, 8), (-1100, -585, 56), (-800, -700, 8), (-800, -700, 56)):
    crate(x, y, z)
for x, y in ((-1046, -610), (-750, -700), (-960, -520)):
    crate(x, y, 8, pushable=True)
prop('models/ginsmodels/gins_drums.mdl', -900, -470, z=8); prop('models/ginsmodels/gins_drums.mdl', -870, -480, z=8)
# Half-Life's wall chargers in the corner by the door: the H.E.V. charger on the east wall, first aid beside it
# (func_recharge / func_healthcharger; the +0 / +a frames are their ready and empty faces)
hev = box((-732, -464, 24), (-720, -416, 96), {'all': 'RECHARGEEDGE1', 'x-': '+0RECHARGE'},
          **{'x-': fit((0, -1, 0), (0, 0, -1), 416, 96, 48, 72, 128, 192)})
ents.append(entity({'classname': 'func_recharge'}, [hev]))
aid = box((-776, -408, 40), (-744, -400, 88), {'all': 'MEDKITEDGE1', 'y-': '+0MEDKIT'},
          **{'y-': fit((1, 0, 0), (0, 0, -1), -776, 88, 32, 48, 64, 96)})
ents.append(entity({'classname': 'func_healthcharger'}, [aid]))
FURNITURE.append((-732, -464, -720, -416)); FURNITURE.append((-776, -408, -744, -400))

# the little house: a living room and a bathroom corner
ix0, iy0, ix1, iy1 = building(-256, -640, 0, -416, 160, 'PRXBRICK1A', 'house', 'y+', windows=1, roof='SLATE_ROOF_1', gable=48)
prop('models/ginsmodels/gins_couch.mdl', ix0 + 4, -540, yaw=0, z=8)
prop('models/ginsmodels/wb_table01.mdl', -150, -540, z=8); prop('models/chair.mdl', -110, -540, yaw=180, z=8)
prop('models/ginsmodels/gins_toilet.mdl', ix1 - 20, iy0 + 40, yaw=180, z=8); prop('models/ginsmodels/gins_sink.mdl', ix1 - 2, iy0 + 90, yaw=180, z=8)
prop('models/ginsmodels/lag_radio.mdl', -150, -540, yaw=90, z=8 + 30)

# ---------------------------------------------------------------- cars (brush-built, like classic HL maps)
def extrude_y(poly_xz, y0, y1, cap, sides):
    b = Brush()
    b.face([(x, y1, z) for x, z in poly_xz], cap)
    b.face([(x, y0, z) for x, z in reversed(poly_xz)], cap)
    for i in range(len(poly_xz)):
        (xa, za), (xb, zb) = poly_xz[i], poly_xz[(i + 1) % len(poly_xz)]
        b.face([(xa, y0, za), (xb, y0, zb), (xb, y1, zb), (xa, y1, za)], sides[i] if isinstance(sides, list) else sides)
    return b


def car(cx, cy, along_y, color, wrecked=False, z=2, lightbar=False):
    CARS.append((cx, cy, along_y))
    """a sedan, 184 long; along_y turns it 90 degrees; z = ground height under it."""
    paintt, sidet = 'car_' + color, 'carside_' + color
    def P(x, y, zz):
        return (cx - y, cy + x, zz + z) if along_y else (cx + x, cy + y, zz + z)
    brushes = []
    def add(b):
        for f in b.faces:
            f[0] = [P(*v) for v in f[0]]
        brushes.append(b)
    L = 88
    # body: sides carry the door texture, front the grille, back the tail lights
    lu = (0, 1, 0) if along_y else (1, 0, 0)
    side_fit = fit(lu, (0, 0, -1), (cy if along_y else cx) - L, 34 + z, 2 * L, 22, 256, 64)
    wu = (1, 0, 0) if along_y else (0, 1, 0)
    end_fit = fit(wu, (0, 0, -1), (cx if along_y else cy) - 36, 34 + z, 72, 22, 128, 32)
    body = box((-L, -36, 12), (L, 36, 34), {'top': paintt, 'bottom': 'car_under', 'x+': 'car_front', 'x-': 'car_back', 'y+': sidet, 'y-': sidet},
               **{'y+': side_fit, 'y-': side_fit, 'x+': end_fit, 'x-': end_fit})
    add(body)
    add(box((44, -34, 34), (L, 34, 40), paintt))                                      # hood
    add(box((-L, -34, 34), (-56, 34, 40), paintt))                                    # trunk
    add(extrude_y([(-56, 34), (44, 34), (18, 62), (-40, 62)], -32, 32, 'car_window', ['car_window', 'car_window', paintt, 'car_window']))
    if lightbar:
        add(box((-12, -24, 62), (8, 24, 68), {'all': 'car_chrome', 'top': 'lightbar', 'x+': 'lightbar', 'x-': 'lightbar'}))
    add(box((L, -34, 14), (L + 4, 34, 22), 'car_chrome'))                             # bumpers
    add(box((-L - 4, -34, 14), (-L, 34, 22), 'car_chrome'))
    for wx in (56, -56):
        for y0, y1 in ((30, 40), (-40, -30)):
            # wheels are built in world space so the tire texture stays aligned when the car is turned
            if along_y:
                brushes.append(cylinder_x(cy + wx, cx - y1, cx - y0, 14 + z, 14, 8, 'TIRE_01', 'car_under'))
            else:
                brushes.append(cylinder_y(cx + wx, cy + y0, cy + y1, 14 + z, 0, 14, 8, 'TIRE_01', 'car_under'))
    # sc_car (game/dlls/svencraft/sc_car.cpp): smokes when hurt, burns, blows up and turns into its burnt copy
    # (a func_illusionary it takes the model of); spawnflag 1: burnt out already
    wreck = 'sc_wreck%d' % len(CARS)
    kv = {'classname': 'sc_car', 'zhlt_lightflags': '2', 'targetname': 'sc_car', 'wreck': wreck}
    if wrecked:
        kv['spawnflags'] = '1'
    ents.append(entity(kv, brushes))
    burnt = []
    for b in brushes:
        c = Brush()
        c.faces = [[f[0], BURNT.get(f[1], f[1])] + f[2:] for f in b.faces]
        burnt.append(c)
    ents.append(entity({'classname': 'func_illusionary', 'targetname': wreck, 'zhlt_lightflags': '2'}, burnt))


car(-980, 88, False, 'red')
car(-520, 88, False, 'blue')
car(-230, -88, False, 'white')
car(-1000, -620, True, 'green')
car(-860, -620, True, 'black')
car(520, 88, False, 'black')
car(900, 420, True, 'white', wrecked=True, z=int(min(surface_z(900 + dx, 420 + dy) for dx in (-40, 40) for dy in (-90, 90))))  # near the rift

# ---------------------------------------------------------------- the rest of the town (maps_src/town_v3.py)
town_v3.build(globals())

# ---------------------------------------------------------------- street lamps
for x in range(-1300, 501, 400):
    for side in (1, -1):
        y = side * 176
        x2 = x + 200 if side < 0 else x
        world.append(box((x2 - 4, y - 4, 8), (x2 + 4, y + 4, 200), 'car_chrome'))
        world.append(box((x2 - 16, y - 10, 200), (x2 + 16, y + 10, 210), {'all': 'car_chrome', 'bottom': 'streetlight1'}))
        ents.append(entity({'classname': 'light', 'origin': '%d %d %d' % (x2, y, 190), '_light': '255 220 160 110'}))

# ---------------------------------------------------------------- props (Sven Co-op models)
trees = ['models/hunger/vegitation/tree1.mdl', 'models/hunger/vegitation/tree2.mdl', 'models/ginsmodels/lag_oaktree.mdl',
         'models/hunger/vegitation/zalec_tree1.mdl']   # (models/tree.mdl is Half-Life's Xen tree: by the rift below)
placed = 0
while placed < 70:
    x, y = rng.uniform(-H + 200, H - 200), rng.uniform(-H + 200, H - 200)
    if flat_dist(x, y) < 120 or math.hypot(x - RIFT[0], y - RIFT[1]) < RIFT[2] + 120:
        continue
    prop(rng.choice(trees), x, y, solid=False)
    placed += 1
for _ in range(40):
    x, y = rng.uniform(-H + 200, H - 200), rng.uniform(-H + 200, H - 200)
    if flat_dist(x, y) < 60 or math.hypot(x - RIFT[0], y - RIFT[1]) < RIFT[2] + 60:
        continue
    prop(rng.choice(['models/hunger/vegitation/bush1.mdl', 'models/hunger/vegitation/bush2.mdl', 'models/hunger/vegitation/fern1.mdl',
                     'models/snd/rock_L1.mdl', 'models/snd/rock_L2.mdl', 'models/big_rock.mdl']), x, y, solid=False)
for x, y in ((-700, -300), (-690, -340)):
    prop('models/ginsmodels/gins_drums.mdl', x, y, z=2)
for x, y in ((-660, -310), (-640, -280)):
    # fuel drums: shoot them (game/dlls/svencraft/sc_car.cpp)
    ents.append(entity({'classname': 'sc_barrel', 'origin': '%d %d 4' % (x, y), 'angles': '0 %d 0' % rng.randint(0, 359)}))
for x, y in ((-620, -420), (-600, -470)):
    prop('models/big_rock.mdl', x, y)
for x, y in ((-1150, 330), (-700, 330), (-420, 330), (-120, -330)):
    prop('models/ginsmodels/gins_trashcan.mdl', x, y, yaw=90, z=8)
for x in (-1050, -500):
    prop('models/ginsmodels/bench3.mdl', x, 300, yaw=270, z=8)
prop('models/snd/sandbags_straight.mdl', 760, 520, yaw=60, z=None)
prop('models/snd/sandbags_curved.mdl', 820, 610, yaw=20, z=None)

# the monsters already in the town at the start (spawned below)
MONSTERS = (('monster_zombie', -1000, 600, 270), ('monster_headcrab', -500, 520, 0), ('monster_headcrab', -1110, -470, 90),
           ('monster_zombie', -930, -460, 90), ('monster_houndeye', 660, 860, 180), ('monster_houndeye', 700, 940, 200),
           ('monster_zombie', 620, -640, 150), ('monster_headcrab', 680, 420, 200), ('monster_bullchicken', -200, 1100, 270))

# ---------------------------------------------------------------- the rift
ents.append(entity({'classname': 'info_sc_rift', 'origin': '%d %d 0' % (RIFT[0], RIFT[1]), 'radius': str(RIFT[2]), 'height': '72'}))
# Xen leaks through it: Half-Life's Xen flora on the ground around it (the trees lash whoever comes close, the light
# plants pull in, the spores can be shot)
def rift_ground(x, y):
    """on realistic ground: outside the cells the rift removed"""
    cx, cy = (x + H) // G * G - H + G / 2, (y + H) // G * G - H + G / 2
    return math.hypot(cx - RIFT[0], cy - RIFT[1]) >= RIFT[2]


xrng, xen = random.Random(23), []
for cls, n, room in (('xen_tree', 3, 110), ('xen_plantlight', 5, 60), ('xen_spore_large', 1, 90), ('xen_spore_medium', 2, 60),
                     ('xen_spore_small', 3, 40), ('xen_hair', 6, 30)):
    k = 0
    while k < n:
        a, r = xrng.uniform(0, 2 * math.pi), RIFT[2] + xrng.uniform(60, 240)
        x, y = RIFT[0] + r * math.cos(a), RIFT[1] + r * math.sin(a)
        if (not rift_ground(x, y) or y < 380 or abs(x) > H - 300 or abs(y) > H - 300 or math.hypot(x - 900, y - 420) < 160
                or any(math.hypot(x - mx, y - my) < 100 for _, mx, my, _ in MONSTERS)
                or any(math.hypot(x - ox, y - oy) < room + oroom for ox, oy, oroom in xen)):
            continue
        xen.append((x, y, room))
        if cls != 'xen_hair':
            FURNITURE.append((x - room / 2, y - room / 2, x + room / 2, y + room / 2))   # no AI nodes in them
        ents.append(entity({'classname': cls, 'origin': '%d %d %d' % (x, y, surface_z(x, y) - 2), 'angles': '0 %d 0' % xrng.randint(0, 359)}))
        k += 1

# ---------------------------------------------------------------- players, weapons, monsters
ents.append(entity({'classname': 'info_player_start', 'origin': '-760 0 40', 'angles': '0 0 0'}))
for k in range(6):
    ents.append(entity({'classname': 'info_player_deathmatch', 'origin': '%d %d 40' % (-760 + 48 * k, 48 * (k % 2) - 24), 'angles': '0 0 0'}))
for cls, x, y, z in (('weapon_crowbar', -700, 40, 16), ('weapon_9mmhandgun', -700, -40, 16), ('ammo_9mmclip', -660, -40, 16),
                     ('ammo_9mmclip', -660, 40, 16), ('weapon_shotgun', -960, 560, 24), ('ammo_buckshot', -920, 560, 24),
                     ('item_healthkit', -480, 520, 24), ('item_battery', -940, -560, 24), ('weapon_9mmAR', -140, -500, 24), ('ammo_9mmAR', -100, -500, 24)):
    ents.append(entity({'classname': cls, 'origin': '%d %d %d' % (x, y, z)}))
for cls, x, y, yaw in MONSTERS:
    ents.append(entity({'classname': cls, 'origin': '%d %d %d' % (x, y, surface_z(x, y) + 48), 'angles': '0 %d 0' % yaw}))
# the first creatures from the block world, on the rift's mound (they drop onto it once it exists)
for x, y, yaw in ((1000, 650, 200), (1060, 930, 240)):
    ents.append(entity({'classname': 'monster_creeper', 'origin': '%d %d 200' % (x, y), 'angles': '0 %d 0' % yaw}))

# ---------------------------------------------------------------- AI nodes: Half-Life monsters path between them
def node_blocked(x, y, pad):
    for x0, y0, x1, y1 in BUILDINGS:
        near = x0 - pad < x < x1 + pad and y0 - pad < y < y1 + pad
        inside = x0 + 16 + pad < x < x1 - 16 - pad and y0 + 16 + pad < y < y1 - 16 - pad
        if near and not inside:
            return True            # in a wall or right against one
    for fx0, fy0, fx1, fy1 in FURNITURE:
        if fx0 - pad / 2 < x < fx1 + pad / 2 and fy0 - pad / 2 < y < fy1 + pad / 2:
            return True
    for cx, cy, ay in CARS:
        hx, hy = (60, 112) if ay else (112, 60)
        if abs(x - cx) < hx + pad / 2 and abs(y - cy) < hy + pad / 2:
            return True
    if ground_z(x, y) < POND[4] + 8:
        return True            # in the pond: Half-Life's walkers don't swim
    return math.hypot(x - RIFT[0], y - RIFT[1]) < RIFT[2] + 48   # the rift's blocks only exist in the game


def node_z(x, y):
    for x0, y0, x1, y1 in BUILDINGS:
        if x0 < x < x1 and y0 < y < y1:
            return 8           # a building's floor slab
    return max(ground_z(x, y), 8)


NODE_STEP = 176
node_pts = [(gx, gy) for gx in range(-H + 176, H - 175, NODE_STEP) for gy in range(-H + 176, H - 175, NODE_STEP)]
for x0, y0, x1, y1 in BUILDINGS:                       # a few inside every building
    for fx in (0.3, 0.7):
        for fy in (0.3, 0.7):
            node_pts.append((int(x0 + (x1 - x0) * fx), int(y0 + (y1 - y0) * fy)))
for dx_, dy_, nx_, ny_ in DOORS:                       # and either side of each doorway
    node_pts += [(dx_ + nx_ * 56, dy_ + ny_ * 56), (dx_ - nx_ * 64, dy_ - ny_ * 64)]
nodes = 0
for x, y in node_pts:
    if node_blocked(x, y, 40) and not any(abs(x - d[0]) < 80 and abs(y - d[1]) < 80 for d in DOORS):
        continue
    ents.append(entity({'classname': 'info_node', 'origin': '%d %d %d' % (x, y, node_z(x, y) + 32)}))
    nodes += 1
print('AI nodes', nodes)

# ---------------------------------------------------------------- write and compile
wads = [wadpath] + [os.path.join(SVEN, w) for w in ('halflife.wad', 'Opfor.wad', 'tfc.WAD', 'tfc2.wad', 'bridge3.wad', 'op4ctf.wad', 'nw.wad', 'barney.wad', 'decay.wad',
                                                 'cs_bdog.wad', 'neilm4.wad', 'neilm5.wad', 'deathmission.wad', 'neilm2.wad',
                                                 'liquids.wad')]
ws = {'classname': 'worldspawn', 'mapversion': '220', 'wad': ';'.join(wads), 'skyname': 'grassy', 'message': 'Svencraft Sandbox', 'maxrange': '8192',
      'sc_blocktop': str(SLAB // 40)}   # the block world fills everything under the realistic ground
sun = {'classname': 'light_environment', 'origin': '0 0 1500', 'pitch': '-48', 'angles': '0 210 0',
       '_light': '255 238 205 330', '_diffuse_light': '140 165 215 130'}
# the light compiler doesn't know the diggable geometry: a copy of it casts the shadows on the map's brush
# entities (cars, doors, crates, glass) and is removed when the map starts (sc_world.cpp)
def plain(brush):
    c = Brush()
    c.faces = [[f[0], 'OUT_CONCRETE1', None, None, (0, 0), (1, 1)] for f in brush.faces]
    return c


ents.append(entity({'classname': 'func_wall', 'targetname': 'sc_shadow', 'zhlt_lightflags': '2', 'zhlt_noclip': '1'}, [plain(b) for b, m, c in dyn]))
# a light haze in the distance (env_fog, game/dlls/svencraft/sc_fog.cpp): the far hills and streets soften toward the
# horizon's colour; the sky stays clear
ents.append(entity({'classname': 'env_fog', 'targetname': 'town_haze', 'origin': '0 0 200', 'rendercolor': '205 210 225',
                    'iuser2': '1200', 'iuser3': '9000'}))
text = entity(ws, world) + entity(sun) + ''.join(ents)
open(os.path.join(HERE, NAME + '.map'), 'w', newline='\n').write(text)
print('brushes: world %d, entities %d' % (len(world), len(ents)))
def texsize(name):
    if name in TEX:
        return TEX[name].shape[1], TEX[name].shape[0]
    im, _ = wadtex.load(name)
    return im.size


nb, nt = write_dyn(os.path.join(HERE, NAME + '.dyn'), dyn, texsize)
shutil.copy2(os.path.join(HERE, NAME + '.dyn'), os.path.join(GAME, 'maps', NAME + '.dyn'))
print('diggable brushes %d (%d textures)' % (nb, nt))
# the renderer finds diggable textures by name in the game's WADs: ship the exact ones the map compiler used
dyn_tex = sorted({f[1] for b, m, c in dyn for f in b.faces} | {c for b, m, c in dyn})
wadtex.write_raw_wad(os.path.join(GAME, 'svencraft_dyn.wad'), [t for t in dyn_tex if t not in TEX])
bsp = compile_map(HERE, NAME)
shutil.copy2(bsp, os.path.join(GAME, 'maps', NAME + '.bsp'))
print('installed', os.path.getsize(bsp))
